// Copyright 2025 OfficeCli (officecli.ai)
// SPDX-License-Identifier: Apache-2.0

// Bug confirmation tests generated by fuzzer.
// Each test confirms a specific bug found during fuzz testing.
// Tests are named BugFN_Description for easy tracking.

using FluentAssertions;
using OfficeCli;
using OfficeCli.Core;
using OfficeCli.Handlers;
using Xunit;

namespace OfficeCli.Tests.Functional;

public class FuzzBugTests : IDisposable
{
    private readonly string _pptxPath;
    private readonly string _xlsxPath;
    private readonly string _docxPath;

    public FuzzBugTests()
    {
        _pptxPath = Path.Combine(Path.GetTempPath(), $"fuzzbugs_{Guid.NewGuid():N}.pptx");
        _xlsxPath = Path.Combine(Path.GetTempPath(), $"fuzzbugs_{Guid.NewGuid():N}.xlsx");
        _docxPath = Path.Combine(Path.GetTempPath(), $"fuzzbugs_{Guid.NewGuid():N}.docx");
        BlankDocCreator.Create(_pptxPath);
        BlankDocCreator.Create(_xlsxPath);
        BlankDocCreator.Create(_docxPath);

        using var pptx = new PowerPointHandler(_pptxPath, editable: true);
        pptx.Add("/", "slide", null, new());
        pptx.Add("/slide[1]", "shape", null, new() { ["text"] = "Hello", ["x"] = "2cm", ["y"] = "2cm", ["width"] = "10cm", ["height"] = "3cm" });
    }

    public void Dispose()
    {
        if (File.Exists(_pptxPath)) File.Delete(_pptxPath);
        if (File.Exists(_xlsxPath)) File.Delete(_xlsxPath);
        if (File.Exists(_docxPath)) File.Delete(_docxPath);
    }

    // ==================== Bug F1: ParseFontSize accepts NaN/Infinity ====================

    [Fact]
    public void BugF1_ParseFontSize_NaN_ShouldThrowArgumentException()
    {
        // BUG: double.TryParse("NaN") succeeds in C#, so ParseFontSize silently returns NaN
        var act = () => ParseHelpers.ParseFontSize("NaN");
        act.Should().Throw<ArgumentException>("NaN is not a valid font size");
    }

    [Fact]
    public void BugF1_ParseFontSize_Infinity_ShouldThrowArgumentException()
    {
        var act = () => ParseHelpers.ParseFontSize("Infinity");
        act.Should().Throw<ArgumentException>("Infinity is not a valid font size");
    }

    [Fact]
    public void BugF1_ParseFontSize_NegativeInfinity_ShouldThrowArgumentException()
    {
        var act = () => ParseHelpers.ParseFontSize("-Infinity");
        act.Should().Throw<ArgumentException>("-Infinity is not a valid font size");
    }

    [Fact]
    public void BugF1_Pptx_SetShapeSize_NaN_ShouldThrowArgumentException()
    {
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["size"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN font size should be rejected");
    }

    [Fact]
    public void BugF1_Docx_SetRunSize_NaN_ShouldThrowArgumentException()
    {
        using var handler = new WordHandler(_docxPath, editable: true);
        handler.Add("/body", "paragraph", null, new() { ["text"] = "Hello" });
        var act = () => handler.Set("/body/p[1]/r[1]", new() { ["size"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN font size should be rejected");
    }

    [Fact]
    public void BugF1_Docx_SetRunSize_Infinity_ShouldThrowArgumentException()
    {
        using var handler = new WordHandler(_docxPath, editable: true);
        handler.Add("/body", "paragraph", null, new() { ["text"] = "Hello" });
        var act = () => handler.Set("/body/p[1]/r[1]", new() { ["size"] = "Infinity" });
        act.Should().Throw<ArgumentException>("Infinity font size should be rejected");
    }

    // ==================== Bug F2: PPTX opacity/rotation accept NaN/Infinity ====================

    [Fact]
    public void BugF2_Pptx_SetOpacity_NaN_ShouldThrowArgumentException()
    {
        // BUG: opacity="NaN" silently accepted, produces NaN in OOXML numeric field
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        handler.Set("/slide[1]/shape[1]", new() { ["fill"] = "FF0000" });
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["opacity"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN opacity should be rejected");
    }

    [Fact]
    public void BugF2_Pptx_SetOpacity_Infinity_ShouldThrowArgumentException()
    {
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        handler.Set("/slide[1]/shape[1]", new() { ["fill"] = "FF0000" });
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["opacity"] = "Infinity" });
        act.Should().Throw<ArgumentException>("Infinity opacity should be rejected");
    }

    [Fact]
    public void BugF2_Pptx_SetRotation_NaN_ShouldThrowArgumentException()
    {
        // BUG: rotation="NaN" silently accepted
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["rotation"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN rotation should be rejected");
    }

    [Fact]
    public void BugF2_Pptx_SetRotation_Infinity_ShouldThrowArgumentException()
    {
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["rotation"] = "Infinity" });
        act.Should().Throw<ArgumentException>("Infinity rotation should be rejected");
    }

    // ==================== Bug F3: EmuConverter throws FormatException instead of ArgumentException ====================

    [Fact]
    public void BugF3_EmuConverter_InvalidValue_ShouldThrowArgumentException_NotFormatException()
    {
        // BUG: EmuConverter.ParseEmu throws FormatException; callers expect ArgumentException
        // AI agents using catch(ArgumentException) will miss these errors
        var act = () => EmuConverter.ParseEmu("abc");
        act.Should().Throw<ArgumentException>("invalid EMU values should throw ArgumentException, not FormatException");
    }

    [Fact]
    public void BugF3_EmuConverter_EmptyValue_ShouldThrowArgumentException_NotFormatException()
    {
        var act = () => EmuConverter.ParseEmu("");
        act.Should().Throw<ArgumentException>("empty EMU value should throw ArgumentException, not FormatException");
    }

    [Fact]
    public void BugF3_Pptx_SetShapeX_InvalidValue_ShouldThrowArgumentException()
    {
        // The bug surfaces at the handler level — FormatException leaks from EmuConverter
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["x"] = "abc" });
        act.Should().Throw<ArgumentException>("invalid x position should throw ArgumentException");
    }

    // ==================== Bug F4: DOCX paragraph alignment silent fallback ====================

    [Fact]
    public void BugF4_Docx_SetParagraphAlignment_InvalidValue_ShouldThrowArgumentException()
    {
        // BUG: alignment="invalid" silently falls back to Left (WordHandler.Set.cs:1556 default branch)
        using var handler = new WordHandler(_docxPath, editable: true);
        handler.Add("/body", "paragraph", null, new() { ["text"] = "Hello" });
        var act = () => handler.Set("/body/p[1]", new() { ["alignment"] = "invalid" });
        act.Should().Throw<ArgumentException>("invalid alignment value should be rejected, not silently fallback to Left");
    }

    [Fact]
    public void BugF4_Docx_SetParagraphAlignment_EmptyValue_ShouldThrowArgumentException()
    {
        using var handler = new WordHandler(_docxPath, editable: true);
        handler.Add("/body", "paragraph", null, new() { ["text"] = "Hello" });
        var act = () => handler.Set("/body/p[1]", new() { ["alignment"] = "" });
        act.Should().Throw<ArgumentException>("empty alignment value should be rejected");
    }

    [Fact]
    public void BugF4_Docx_SetParagraphAlignment_Middle_ShouldThrowArgumentException()
    {
        using var handler = new WordHandler(_docxPath, editable: true);
        handler.Add("/body", "paragraph", null, new() { ["text"] = "Hello" });
        var act = () => handler.Set("/body/p[1]", new() { ["alignment"] = "middle" });
        act.Should().Throw<ArgumentException>("'middle' is not a valid Word alignment (valid: left, center, right, justify)");
    }

    // ==================== Bug F2 extension: lineOpacity/lineSpacing/spaceBefore accept NaN/Infinity ====================

    [Fact]
    public void BugF2b_Pptx_SetLineOpacity_NaN_ShouldThrowArgumentException()
    {
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        handler.Set("/slide[1]/shape[1]", new() { ["line"] = "FF0000" });
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["lineopacity"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN lineOpacity should be rejected");
    }

    [Fact]
    public void BugF2b_Pptx_SetLineSpacing_NaN_ShouldThrowArgumentException()
    {
        // BUG: lineSpacing="NaN" — double.TryParse succeeds, NaN×100000 = garbage stored in OOXML
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["lineSpacing"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN lineSpacing should be rejected");
    }

    [Fact]
    public void BugF2b_Pptx_SetSpaceBefore_NaN_ShouldThrowArgumentException()
    {
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["spaceBefore"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN spaceBefore should be rejected");
    }

    [Fact]
    public void BugF2b_Pptx_SetCharSpacing_NaN_ShouldThrowArgumentException()
    {
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["spacing"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN charSpacing should be rejected");
    }

    // ==================== Bug F9: PPTX lineDash invalid values silent fallback to Solid ====================

    [Fact]
    public void BugF9_Pptx_SetLineDash_InvalidValue_ShouldThrowArgumentException()
    {
        // BUG: lineDash switch has `_ => Solid` fallback at PowerPointHandler.ShapeProperties.cs:336
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["linedash"] = "invalid" });
        act.Should().Throw<ArgumentException>("'invalid' lineDash should be rejected, not silently fallback to Solid");
    }

    [Fact]
    public void BugF9_Pptx_SetLineDash_EmptyValue_ShouldThrowArgumentException()
    {
        using var handler = new PowerPointHandler(_pptxPath, editable: true);
        var act = () => handler.Set("/slide[1]/shape[1]", new() { ["linedash"] = "" });
        act.Should().Throw<ArgumentException>("empty lineDash should be rejected");
    }

    // ==================== Bug F10: XLSX alignment.horizontal invalid values silent null ====================

    [Fact]
    public void BugF10_Xlsx_SetAlignmentHorizontal_InvalidValue_ShouldThrowArgumentException()
    {
        // BUG: ParseHAlign returns null for unknown values (ExcelStyleManager.cs:764)
        // null is set on alignment.Horizontal — silently no-op
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["alignment.horizontal"] = "invalid" });
        act.Should().Throw<ArgumentException>("'invalid' horizontal alignment should be rejected");
    }

    [Fact]
    public void BugF10_Xlsx_SetAlignmentHorizontal_EmptyValue_ShouldThrowArgumentException()
    {
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["alignment.horizontal"] = "" });
        act.Should().Throw<ArgumentException>("empty horizontal alignment should be rejected");
    }

    // ==================== Bug F11: XLSX font.size NaN/Infinity silent acceptance ====================

    [Fact]
    public void BugF11_Xlsx_SetFontSize_NaN_ShouldThrowArgumentException()
    {
        // BUG: ExcelStyleManager.cs:297 — double.TryParse("NaN") succeeds, NaN used as font size
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["font.size"] = "NaN" });
        act.Should().Throw<ArgumentException>("NaN font.size should be rejected");
    }

    [Fact]
    public void BugF11_Xlsx_SetFontSize_Infinity_ShouldThrowArgumentException()
    {
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["font.size"] = "Infinity" });
        act.Should().Throw<ArgumentException>("Infinity font.size should be rejected");
    }

    [Fact]
    public void BugF11_Xlsx_SetFontSize_InvalidString_ShouldThrowArgumentException()
    {
        // BUG: ExcelStyleManager.cs:297 — TryParse failure silently uses base font size (no error)
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["font.size"] = "abc" });
        act.Should().Throw<ArgumentException>("invalid font.size string should be rejected, not silently ignored");
    }

    // ==================== Bug F4 extension: DOCX Add also has alignment silent fallback ====================

    [Fact]
    public void BugF4b_Docx_AddParagraph_InvalidAlignment_ShouldThrowArgumentException()
    {
        // BUG: WordHandler.Add.cs:63 — same `_ => JustificationValues.Left` pattern as Set
        using var handler = new WordHandler(_docxPath, editable: true);
        var act = () => handler.Add("/body", "paragraph", null,
            new() { ["text"] = "Hello", ["alignment"] = "invalid" });
        act.Should().Throw<ArgumentException>("invalid alignment in Add should be rejected");
    }

    // ==================== Bug F10 extension: XLSX alignment.vertical invalid values also silent null ====================

    [Fact]
    public void BugF10b_Xlsx_SetAlignmentVertical_InvalidValue_ShouldThrowArgumentException()
    {
        // BUG: ExcelStyleManager.cs:773 — ParseVAlign `_ => null`, same issue as ParseHAlign
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["alignment.vertical"] = "invalid" });
        act.Should().Throw<ArgumentException>("'invalid' vertical alignment should be rejected");
    }

    // ==================== Bug F5: XLSX border.all invalid values silent failure ====================

    [Fact]
    public void BugF5_Xlsx_SetBorderAll_InvalidValue_ShouldThrowArgumentException()
    {
        // BUG: border.all="invalid" silently ignored — no exception, no effect
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["border.all"] = "invalid" });
        act.Should().Throw<ArgumentException>("'invalid' is not a valid border style and should be rejected");
    }

    [Fact]
    public void BugF5_Xlsx_SetBorderAll_EmptyValue_ShouldThrowArgumentException()
    {
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["border.all"] = "" });
        act.Should().Throw<ArgumentException>("empty border style should be rejected");
    }

    [Fact]
    public void BugF5_Xlsx_SetBorderAll_SolidNotValid_ShouldThrowArgumentException()
    {
        // 'solid' is a CSS border style, not a valid Excel border style (valid: thin, medium, thick, etc.)
        using var handler = new ExcelHandler(_xlsxPath, editable: true);
        handler.Add("/Sheet1", "cell", null, new() { ["ref"] = "A1", ["value"] = "test" });
        var act = () => handler.Set("/Sheet1/A1", new() { ["border.all"] = "solid" });
        act.Should().Throw<ArgumentException>("'solid' is not a valid Excel border style");
    }
}
